<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class ArticleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|max:125',
        ];
    }
    
    public function messages()
	{
		return [
			'title.required' => '文章标题不能为空',
			'title.max'		 =>  '文章标题不能超过125个字符',
		];
//		return parent::messages(); // TODO: Change the autogenerated stub
	}
}
